   ---
   - name: Install Apache
     package:
       name: apache2
       state: present
     when: ansible_os_family == "Debian"

   - name: Install Apache (CentOS)
     package:
       name: httpd
       state: present
     when: ansible_os_family == "RedHat"

   - name: Ensure Apache is running
     service:
       name: "{{ ansible_service_mgr }}"
       state: restarted
       enabled: yes
