pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'exam', url: 'https://github.com/Roma-uuu/codeby-devops.git'
            }
        }
        stage('Build') {
            steps {
                dir('exam/src') {
                    sh 'mvn clean package -Dcheckstyle.skip=true'
                }
            }
        }
        stage('Test Docker Access') {
            steps {
                sh 'docker info'
            }
        }
        stage('Build and Push Docker Image') {
            steps {
                dir('exam/src') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_TOKEN')]) {
                        sh '''
                        echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
                        docker build -t apkerigz/devops:v.0.0.44 .
                        docker push apkerigz/devops:v.0.0.44
                        '''
                    }
                }
            }
        }
        stage('Verify Files') {
            steps {
                sh 'ls -la exam/src/k8s/'
            }
        }
        stage('Check kubectl') {
            steps {
                sh 'which kubectl || echo "kubectl not found"'
                sh 'kubectl version --client || echo "kubectl not available"'
            }
        }
        stage('Test Kubernetes Connection') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG_FILE')]) {
                    sh 'kubectl --kubeconfig=$KUBECONFIG_FILE cluster-info'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG_FILE')]) {
                    sh '''
                    kubectl --kubeconfig=$KUBECONFIG_FILE apply -f exam/src/k8s/deployment.yaml
                    kubectl --kubeconfig=$KUBECONFIG_FILE apply -f exam/src/k8s/service.yaml
                    '''
				}
			}
		}
	}
}
