apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJME1EZ3lOREl3TWpJd05sb1hEVE0wTURneU16SXdNakl3Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEg2CkpjMEtpcTVFcWpSbnovb2Vjcmg0anlkL1orcnJUQnJwY0EzQ1dFMFdwdE5OTzlLV1piQ1I0UHdudzBCR0N2NkwKSWZmL0w2YnJQb3c2UzAwUXBNK0tsbzFHMG9nOU1KUVRQdWtwY0pGbGlsVHlpOWR4elJVREhTUzlNNXR4YjVsVworb0hxaGpndXZDbklXc1ZWc0xiQ0NWL1RPRHErNEt6QXhJaVJkTUwrbHJaY3BiWkdUL1dxMFRlaDZURFY3eXpHCi9adWxwcUxLWUszQXZvV2xNOXdQWmZtR2R2Qk94UjRVNDNXTzAvOXJvTnpNL0hpbWRzTnpuOWIyU1dIRit0QXEKTUpmczB5SjNOU1ZaNUtnaWtzU3pFWmNZcWRsVE13bGp2cmh3cjB1MXp3cWNHWEtxM3gyU0RzNkNNNmJvN3I0VQo5NmFJdmtsZ2NKdXNCeG95OU1rQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUNGU5aFI2VXVtdWdaVGVKTkEySHJxb3Rwa0x6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFFOFJhNEpwRwpzRW1lQ2UwemsvckVBdUdDaHhCRFlTZlBzT0ZWTjNIZ1A4a2xRU0ExWGRFZldrMCtuK3RPOXdnL1hGQmFrWXA3CnV6bzVyYXZpWHFTT3hLa2JVV25xZTcyRUIzYWpUM1RyMnhKOFZsNm44VWhDTElyNWFiYllnUy9BR3R3TzYvWmYKZFhqWTNFYWFMSm9NWFpTOUdNU1BMQVFZYzhVK1MxOWdXWEJDdFJkNGlEQ3JhQWU2SUgxM1pNRjM3dWREUVhGago4czhlaHJCREdON25RSkpHUnV2WHJuOWJDWkxBeU9UZ1RBQUJPcWNZZGs4WVpnOGViTno0VGFJK1MrN2dGVHM2ClcxS1JKK0cvQnhTRnc4Z2o4U3IzSkJaVHROYlhWOTZxb3p0NGR6VjBWc0VYUDFzeGk0b2hocGlvNGlkK2RkeDYKQ2QyNVc0Mm1EbC9YUmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.49.2:8443
  name: kubernetes
- cluster:
    certificate-authority: /home/rsshabanov/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 22 Oct 2024 09:49:27 MSK
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: kubernetes
    user: jenkins-sa
  name: jenkins-context
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 22 Oct 2024 09:49:27 MSK
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: jenkins-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImNXc0FxYkZpRllkTGkxM2RNb3dWb3JSQTgxRWZLLXMwU1hRWHhGUzJNaWMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiamVua2lucy1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImEwMzY5M2E1LWE5YWEtNDMyMS1hMWY5LTUwNzg5YjgzYjk5OCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmplbmtpbnMtc2EifQ.f9hXDBYklmVv08fa8_rqzWs6KZ29Q8vk0Gqic9xRsKQo_OGWtj08qU8qDYbEj7vacarg5JLXEKM16WhkEVI9KsjUwOmFdNGGtbVT_9tAVz77cyLJcQ5wc7im6WSxQORvvbwlvf5fRogqKwHyz-PFwsnZKB8Hoi8Vzw-GX2sOHuyFZPCzSCVwxhxoXxozQZ-DkpCQ3EvBNR8u21TaDG6tKaMebwzKOrz9fXFbKouwG5EmNY3lvrBBa0d8CLDc2dlSYSCiITujz9vIbNJcpskgtBFsI22v4d_zjberw_BTd8iBJqtwvcb5grPygFQWzxDd3Exai7-3fdQo2qR6ng07rw
- name: minikube
  user:
    client-certificate: /home/rsshabanov/.minikube/profiles/minikube/client.crt
    client-key: /home/rsshabanov/.minikube/profiles/minikube/client.key
