---
- name: Install monitoring stack on Kubernetes
  hosts: localhost
  tasks:
    - name: Add Helm repository for Prometheus
      community.general.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Add Helm repository for Grafana
      community.general.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts

    - name: Update Helm repositories
      command: helm repo update

    - name: Install Prometheus
      community.general.helm:
        name: prometheus
        chart_ref: prometheus-community/prometheus
        namespace: monitoring
        create_namespace: true
        release_state: present

    - name: Install Grafana
      community.general.helm:
        name: grafana
        chart_ref: grafana/grafana
        namespace: monitoring
        release_state: present
        set:
          - adminPassword=admin
          - service.type=NodePort
          - service.nodePort=32000

    - name: Wait for Grafana pod to be ready
      community.kubernetes.k8s_info:
        api_version: v1
        kind: Pod
        namespace: monitoring
        labels:
          app.kubernetes.io/name: grafana
      register: grafana_pods

    - name: Wait for Grafana to be fully ready
      pause:
        seconds: 15
