ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'
Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/bionic64"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.hostname = "server"
    server.vm.provision "shell", path: "provision_server.sh"
  end

  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/bionic64"
    client.vm.network "private_network", ip: "192.168.56.11"
    client.vm.hostname = "client"
    client.vm.provision "shell", path: "provision_client.sh"
  end
end
