ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'
   Vagrant.configure("2") do |config|
     config.vm.define "dev" do |dev|
       dev.vm.box = "ubuntu/bionic64"
       dev.vm.network "private_network", type: "dhcp"
       dev.vm.hostname = "dev"
       dev.vm.provision "ansible" do |ansible|
         ansible.playbook = "ansible/playbooks/setup.yml"
       end
     end

     config.vm.define "prod" do |prod|
       prod.vm.box = "ubuntu/bionic64"
       prod.vm.network "private_network", type: "dhcp"
       prod.vm.hostname = "prod"
       prod.vm.provision "ansible" do |ansible|
         ansible.playbook = "ansible/playbooks/setup.yml"
       end
     end
   end
   
